sudo: no
cache:
  directories:
    - $HOME/.cache/pip
language: python
python:
  - "2.6"

addons:
  postgresql: "9.3"

services:
  - rabbitmq
  - memcached

before_install:
  - npm install -g less
  - gem install puppet puppet-lint
  - wget 'https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.10.tar.gz'
  - tar zxf elasticsearch-0.90.10.tar.gz
  # Note! bin/elasticsearch will start ES in the background automatically.
  #    # That's why this works without using a service or a trailing &
  - ./elasticsearch-0.90.10/bin/elasticsearch
  - pip install --no-deps -r requirements.txt

install: true

before_script:
    - psql -c "create user test with encrypted password 'aPassword' superuser;" -U postgres
    - psql -c 'create database socorro_test;' -U postgres
    - psql -c 'create database socorro_integration_test;' -U postgres
    - psql -c 'create database socorro_migration_test;' -U postgres

script:
  - ./scripts/build.sh

notifications:
  webhooks: http://leeroybot.lonnen.com/hubot/travis?room=%23breakpad
